name: busybox

on:
  pull_request:
    paths:
      - "images/busybox/**"
      - "hack/**"
      - ".github/workflows/build-image.yaml"
      - ".github/workflows/busybox.yaml"
  push:
    branches: [main]
    paths:
      - "images/busybox/**"
      - "hack/**"
      - ".github/workflows/build-image.yaml"
      - ".github/workflows/busybox.yaml"
  schedule:
    - cron: "17 6 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build-image.yaml
    with:
      image: busybox
    secrets: inherit
